package com.jas.seckill.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Goods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.nameDesc
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private String namedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.randomName
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private String randomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.imageURL
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.store
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Integer store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.startTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.endTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.nameDesc
     *
     * @return the value of goods.nameDesc
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public String getNamedesc() {
        return namedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.nameDesc
     *
     * @param namedesc the value for goods.nameDesc
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setNamedesc(String namedesc) {
        this.namedesc = namedesc == null ? null : namedesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.randomName
     *
     * @return the value of goods.randomName
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public String getRandomname() {
        return randomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.randomName
     *
     * @param randomname the value for goods.randomName
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setRandomname(String randomname) {
        this.randomname = randomname == null ? null : randomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.imageURL
     *
     * @return the value of goods.imageURL
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.imageURL
     *
     * @param imageurl the value for goods.imageURL
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.store
     *
     * @return the value of goods.store
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Integer getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.store
     *
     * @param store the value for goods.store
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setStore(Integer store) {
        this.store = store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.startTime
     *
     * @return the value of goods.startTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.startTime
     *
     * @param starttime the value for goods.startTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.endTime
     *
     * @return the value of goods.endTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.endTime
     *
     * @param endtime the value for goods.endTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}