package com.jas.seckill.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Orders implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsId
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.buyNum
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Integer buynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.buyPrice
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private BigDecimal buyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderMoney
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private BigDecimal ordermoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.createTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsId
     *
     * @return the value of orders.goodsId
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsId
     *
     * @param goodsid the value for orders.goodsId
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.buyNum
     *
     * @return the value of orders.buyNum
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Integer getBuynum() {
        return buynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.buyNum
     *
     * @param buynum the value for orders.buyNum
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setBuynum(Integer buynum) {
        this.buynum = buynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.buyPrice
     *
     * @return the value of orders.buyPrice
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public BigDecimal getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.buyPrice
     *
     * @param buyprice the value for orders.buyPrice
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderMoney
     *
     * @return the value of orders.orderMoney
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public BigDecimal getOrdermoney() {
        return ordermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderMoney
     *
     * @param ordermoney the value for orders.orderMoney
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setOrdermoney(BigDecimal ordermoney) {
        this.ordermoney = ordermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.createTime
     *
     * @return the value of orders.createTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.createTime
     *
     * @param createtime the value for orders.createTime
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbggenerated Sun Jul 15 16:07:40 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}